[2024-07-11T14:36:46.707+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Addition_Pipeline.tsk_addtion_of_numbers manual__2024-07-11T14:34:30.268961+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
