[2024-07-11T14:03:54.254+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T14:03:54.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Addition_Pipeline.tsk_addtion_of_numbers manual__2024-07-11T14:03:40.102759+00:00 [queued]>
[2024-07-11T14:03:54.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Addition_Pipeline.tsk_addtion_of_numbers manual__2024-07-11T14:03:40.102759+00:00 [queued]>
[2024-07-11T14:03:54.322+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-11T14:03:54.347+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): tsk_addtion_of_numbers> on 2024-07-11 14:03:40.102759+00:00
[2024-07-11T14:03:54.358+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T14:03:54.360+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Addition_Pipeline', 'tsk_addtion_of_numbers', 'manual__2024-07-11T14:03:40.102759+00:00', '--job-id', '529', '--raw', '--subdir', 'DAGS_FOLDER/slack_notification_test.py', '--cfg-path', '/tmp/tmpzdmmhprc']
[2024-07-11T14:03:54.361+0000] {standard_task_runner.py:63} INFO - Started process 202 to run task
[2024-07-11T14:03:54.362+0000] {standard_task_runner.py:91} INFO - Job 529: Subtask tsk_addtion_of_numbers
[2024-07-11T14:03:54.441+0000] {task_command.py:426} INFO - Running <TaskInstance: Addition_Pipeline.tsk_addtion_of_numbers manual__2024-07-11T14:03:40.102759+00:00 [running]> on host 7fbd25afd4e9
[2024-07-11T14:03:54.628+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Addition_Pipeline' AIRFLOW_CTX_TASK_ID='tsk_addtion_of_numbers' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T14:03:40.102759+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T14:03:40.102759+00:00'
[2024-07-11T14:03:54.630+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T14:03:54.664+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T14:03:54.665+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/slack_notification_test.py", line 8, in testing_slack_notify
    a = 3 + '4'
        ~~^~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'str'
[2024-07-11T14:03:54.684+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Addition_Pipeline, task_id=tsk_addtion_of_numbers, run_id=manual__2024-07-11T14:03:40.102759+00:00, execution_date=20240711T140340, start_date=20240711T140354, end_date=20240711T140354
[2024-07-11T14:03:54.715+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 529 for task tsk_addtion_of_numbers (unsupported operand type(s) for +: 'int' and 'str'; 202)
[2024-07-11T14:03:54.739+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T14:03:54.772+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T14:03:54.775+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
